config/routes.rb
require 'merchant_storefront_constraint'

Monthly::Application.routes.draw do

  # Authentication callbacks
  match "auth/:provider/callback" => 'authentications#create'
  match "auth/failure" => 'authentications#failure'

  # Resources
  resources :category_groups, only: [:show]
  resources :categories, only: [:index, :show] do
    collection do
      get :highlights
    end
  end
  resources :tags, only: [:show] do
    member do
      get :highlights
    end
  end
  resources :merchants, only: [:new, :create] do
    member do
      get :thank_you
      get :terms
    end
  end
  resources :subscriptions do
    member do
      get :confirm_destroy
      post :reactivate
      get :confirm_reactivate
      get :thank_you
    end
    collection do
      get :totals
    end
  end
  resources :user_preferences, only: [:index, :create, :destroy] do
    collection do
      get :my_preferences
    end
  end
  resources :authentications, only: [:index, :create, :destroy]
  resources :plans, only: [:index, :show] do
    collection do
      get :filtered
    end
    member do
      get :preview
      get :summary
      get :subscription_archive
    end
    resource :configurator, controller: 'plan_configurators', only: [] do
      get :zipcode_confirmation
      post :zipcode_confirmation, action: :zipcode_confirmation_submit
      # Plans#show js routes
      get :display_totals

      # Configurator only stuff
      get :coupon_valid
      get :checkout
      get :confirmation
      post :submit
      post :submit_shipping_info
    end
  end
  resource :settings, controller: 'settings', only: [:edit, :update] do
    collection do
      get :persistent_dismiss
      get :edit_password
      put :update_password
      get :update_location
      post :enter_zip
    end
  end
  resource :billing_info, only: [:new, :show, :edit, :destroy] do
    post :callback
    get :delete
  end
  resources :shipping_infos, except: [:show] do
    member do
      get :edit_confirmation
      get :delete
    end
  end
  resources :coupons, only: [:index] do
    collection do
      get :search
    end
  end
  resources :newsletter_subscribers, only: [:create]
  resources :superhubs, only: [:show]
  resource :search, only: [ :show ]

  # Redeem is Coupons#index
  get 'redeem', to: 'coupons#index', as: :coupons_index

  resources :friends, only: [:new, :create]

  # Active Admin
  begin
    ActiveAdmin.routes(self)
    get '/admin/tags/:id' => 'admin/keyword_tags#show', as: :admin_tag
    get '/admin/transactions/:id' => 'admin/transactions#show', as: :admin_transaction
  rescue ActiveRecord::StatementInvalid, PG::Error
    # See #504 for the problem that prompts this horrible begin/rescue.
    warn "ActiveAdmin tried to access the database, but it's not ready"
  end

  namespace :admin do
    constraints CanAccessResque do
      mount Resque::Server, at: '/resque'
    end
  end

  # Users
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' } do
    get 'sessions/form' => 'sessions#form'
    get 'registrations/form' => 'registrations#form'
    get 'passwords/confirmation' => 'passwords#confirmation'
  end
  as :user do
    post 'user_location' => 'sessions#user_location'
    put 'inactivate' => 'registrations#inactivate', as: :inactivate_user_registrations
    get '/users/sign_out' => 'sessions#destroy'

    # Coupons registration
    get 'users/:coupon_name' => 'registrations#new_with_coupon', as: :coupon_registration
    post 'users/create_with_coupon' => 'registrations#create_with_coupon', as: :create_with_coupon
    match '/register_and_get_a_coupon' => redirect('/users/register_5_dollar_coupon')
  end

  # Static pages
  static_routes = %w(
    home
    deals
    featured
    coming_soon
    about
    how-it-works
    terms_of_service
    affiliate_program
    privacy_policy
    why-monthlys
    what-is-monthlys
    jobs
    quality
    guarantee
    contact
    affiliate-program
    sitemap
    record
    beer
  )
  static_routes.each do |action_name|
    get action_name, to: "pages##{action_name.underscore}", as: action_name.underscore
  end

  post 'contact', to: 'pages#contact_submit'

  # Business static pages (merchant marketing site)
  get "business", to: 'business#home'
  get "business/merchants"
  get "business/platform"
  get "business/marketplace"
  get "business/features"
  get "business/reviews"
  get "business/why"
  get "business/custom"
  get "business/categories"
  get "business/developers"

  # Facebook static pages
  get 'facebook/handpicked', to: 'facebook#handpicked'
  get 'facebook/get_10_off', to: 'facebook#get_10_off'

  # Mail web routes
  get 'mail/affiliate_program', to: 'mail#affiliate_program'
  get 'mail/daily_3', to: 'mail#daily_3'
  get 'mail/grand_opening/:id', to: 'mail#grand_opening'
  get 'mail/coupon_invite_5_friends/:id', to: 'mail#coupon_invite_5_friends'
  get 'mail/coupon_invited_5_friends/:id', to: 'mail#coupon_invited_5_friends'
  get 'mail/coupon_sign_up/:id', to: 'mail#coupon_sign_up'
  get 'mail/coupon_signed_up/:id', to: 'mail#coupon_signed_up'
  get 'mail/coupon_signed_up_10/:id', to: 'mail#coupon_signed_up_10'
  get 'mail/new_merchant/:id', to: 'mail#new_merchant'
  get 'mail/new_preference/:id', to: 'mail#new_preference'
  get 'mail/new_user/:id', to: 'mail#new_user'
  get 'mail/new_user_set_preferences/:id', to: 'mail#new_user_set_preferences'
  get 'mail/set_preferences_reminder', to: 'mail#set_preferences_reminder'
  get 'mail/welcome_channel_leads', to: 'mail#welcome_channel_leads'
  get 'mail/popular_national_subscriptions', to: 'mail#popular_national_subscriptions'
  get 'mail/fathers_day', to: 'mail#fathers_day'
  get 'mail/reactivate_email/:id', to: 'mail#reactivate_email', as: 'reactivate_email'

  # Notification web routes
  get 'mail/giftee_email/:id', to: 'notification_mailer#send_giftee_subscription_email'
  get 'mail/shipments/:id', to: 'notification_mailer#send_user_tracking_number_email', as: 'shipment_email'

  # Root
  root to: 'pages#featured'
  #root to: 'plans#filtered', defaults: { filter: { discover: 'handpicked' } }

  # Marketing
  namespace :marketing, module: 'marketing' do
    resources :newsletters, only: [:show]
    resources :user_attachments, only: [:new, :create]
    resources :pages do
      collection do
        get :rewards
      end
    end
  end
  get 'rewards', to: 'marketing/pages#rewards', as: :rewards

  get 'stickit' => 'marketing/user_attachments#new', as: :stickit

  # Merchant storefront
  scope ':custom_site_url', module: 'merchant_storefront', as: 'merchant_storefront', constraints: MerchantStorefrontSiteConstraint.new do
    match '/', to: 'plans#home'

    resources :plans, only: [:index] do
      collection do
        get :home
      end
    end

    get '/how_it_works', to: 'pages#how_it_works'
    get '/contact', to: 'pages#contact'
    get '/about', to: 'pages#about'
    post '/contact', to: 'pages#contact_submit'
  end

  scope ':custom_site_url', constraints: MerchantStorefrontSiteConstraint.new do
    # Resources
    resources :subscriptions, only: [:index, :show, :destroy] do
      member do
        get :confirm_destroy
        post :reactivate
        get :confirm_reactivate
        get :thank_you
      end
      collection do
        get :totals
      end
    end
    resources :coupons, only: [:index] do
      collection do
        get :search
      end
    end
    resources :plans, only: [:index, :show] do
      collection do
        get :filtered
      end
      member do
        get :preview
      end
      resource :configurator, controller: 'plan_configurators', only: [] do
        # Plans#show js routes
        get :display_totals

        # Configurator only stuff
        get :checkout
        get :confirmation
        get :coupon_valid
        post :submit
        post :submit_billing_info
        post :submit_shipping_info
      end
    end
    resource :settings, controller: 'settings', only: [:edit, :update] do
      get :edit_password
      put :update_password
    end
    resource :billing_info, only: [:new, :show, :edit, :destroy] do
      post :callback
      get :delete
    end
    resources :shipping_infos, except: [:show] do
      member do
        get :edit_confirmation
        get :delete
      end
    end

    # Sign out path
    as :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
  end
end

app/views/shared/_as_seen_on.html.erb
<section class="as-seen-on">
  <h1>As seen on:</h1>
  <ul>
    <li><%= link_to(image_tag('content/press-logos/cnn.png', :alt => "CNN"), "#", :title => "CNN") %></li>
    <li><%= link_to(image_tag('content/press-logos/the-new-york-times.png', :alt => "The New York Times"), "#", :title => "The New York Times") %></li>
    <li><%= link_to(image_tag('content/press-logos/bbc.png', :alt => "BBC"), "#", :title => "BBC") %></li>
    <li><%= link_to(image_tag('content/press-logos/forbes.png', :alt => "Forbes"), "#", :title => "Forbes") %></li>
    <li><%= link_to(image_tag('content/press-logos/the-wall-street-journal.png', :alt => "The Wall Stree Journal"), "#", :title => "The Wall Stree Journal") %></li>
    <li><%= link_to(image_tag('content/press-logos/nbc.png', :alt => "NBC"), "#", :title => "NBC") %></li>
  </ul>
</section>

app/views/shared/_enter_zip.html.erb
<div id="zip-modal" class="hidden">
  <section class="modal-zipcode-form">
    <hgroup>
      <h1>Please enter your zipcode</h1>
      <h2>Find local subscriptions for goods and services</h2>
    </hgroup>

    <div id="messages"></div>

    <%= form_tag '/settings/enter_zip.js', method: 'post', id: 'enter_zip_form' do %>
      <label for="zipcode">Your Zipcode</label>
      <%= text_field_tag :zipcode_str, '', id: 'zipcode' %>
      <%= submit_tag 'Submit', class: 'btn secondary' %>
      <a href="#" class="signin">I'm already a member</a>
    <% end %>
  </section>
</div>

app/views/shared/_error_messages.html.erb
<%
  # Locals
  #   - errors
%>
<% if errors.any? %>
  <div class="message message-block flash-error">
    <strong>Error, please check <%= (errors.count > 1)? 'these fields' : 'this field' %>...</strong>
    <ul class="bullets">
      <% errors.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_get_started.html.erb
<% if show_get_started? %>
  <div class="wrapper clearfix">
    <section class="get_started">
      <div class="tape"></div>
      <div class="box">
        <h1><span>Hi there!</span> Here's all you need to get started...</h1>
        <ol>
          <li>
            <figure>
              <%= image_tag 'get_started_step1.png' %>
              <figcaption><span>1</span> Like it? Flip it on</figcaption>
            </figure>
          </li>
          <li>
            <figure>
              <%= image_tag 'get_started_step2.png' %>
              <figcaption><span>2</span> Pick your options</figcaption>
            </figure>
          </li>
          <li>
            <figure>
              <%= image_tag 'get_started_step3.png' %>
              <figcaption><span>3</span> Confirm and enjoy!</figcaption>
            </figure>
          </li>
        </ol>
        <%= link_to 'Dismiss', '#', class: 'close' %>
      </div>
      <div class="shadow_under"></div>
    </section>
  </div>
<% end %>

app/views/shared/_head.html.erb
<%
  # Locals
  #   - type
%>
<!doctype html>
<!--[if lt IE 7]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class='no-js' lang='en'>
<!--<![endif]-->
  <head>
    <title><%= (yield(:title).blank?)? 'Monthlys - All your subscriptions in one great place' : "#{yield(:title)} - Monthlys".html_safe %></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="description" content="All your subscriptions in one great place" />
    <meta name="author" content="Francesco Pinto, Veronica Rebagliatte, Sebastian Borrazas, Gonzalo Saavedra, Santiago Alonso" />
    <%= csrf_meta_tag %>

    <% if type == :business %>
      <%= stylesheet_link_tag 'business' %>
    <% elsif type == :application %>
      <%= stylesheet_link_tag 'application' %>
    <% elsif type == :merchant_storefront %>
      <%= stylesheet_link_tag 'merchant_storefront/application' %>
      <% if customize? %>
        <style>
          <%= render partial: 'merchant_storefront/shared/merchant_styles', locals: { merchant: @merchant } %>
        </style>
      <% end %>
    <% end %>

    <script type="text/javascript" src="<%= Monthly::Config::JS_DEBUG_REQUIREJS ? '/assets/require.js' : asset('all.js') %>"></script>
    <script type="text/javascript">
      require.config({
        baseUrl: '/assets',
        shim: {
          'lib/jquery.carouFredSel': ['jquery'],
          'lib/jquery.ui': ['jquery'],
          'lib/jquery.infieldlabel': ['jquery'],
          'lib/jquery.flexslider': ['jquery'],
          'lib/jquery.colorbox': ['jquery'],
          'lib/jquery.easing': ['jquery'],
          'lib/jquery.tmpl': ['jquery'],
          'lib/recurly': ['jquery']
        }
      });

      if (typeof window.console === 'undefined') {
        // hax
        window.console = {
          log: function() {}
        };
      }
      var _debug = <%= Monthly::Config::JS_DEBUG.inspect %>;
    </script>

    <% unless Rails.env.development? %>

      <% if admin_user_signed_in? %>
        <!-- Bugherd -->
        <script type='text/javascript'>
          (function (d, t) {
            var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
            bh.type = 'text/javascript';
            bh.src = '//www.bugherd.com/sidebarv2.js?apikey=e1d62d13-f320-4223-b665-fa422901b93b';
            s.parentNode.insertBefore(bh, s);
          })(document, 'script');
        </script>
      <% end %>

      <!-- Google Analytics -->
      <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-28666118-1']);
        _gaq.push(['_setDomainName', 'monthlys.com']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
      </script>
    <% end %>
  </head>

app/views/shared/_header_promo.html.erb
<section class="header_promo">
  <style>
    header.main { margin-top: -32px; background-color: transparent!important;}
    body {background-position: left 28px;}
  </style>
  <div class="wrapper">
    <%= link_to 'Dismiss', '#', class: 'dismiss' %>
    <div class="hanging-coupons"></div>
    <%= link_to new_friend_path, class: 'invite-text' do %>
      <span>Invite your friends and get a $5 coupon</span>
    <% end %>
  </div>
</section>

app/views/shared/_header_promo_fathers_day.html.erb
<section class="header_promo fathers_day">
  <style>
    header.main { margin-top: -32px; }
    body { background-position: left 28px; }
  </style>
  <div class="wrapper">
    <%= link_to 'Dismiss', '#', class: 'dismiss' %>
    <div class="hanging-coupons"></div>
    <%= link_to new_friend_path, class: 'invite-text' do %>
      <span>Celebrate Father's Day and get $5 Subscription Credit!</span>
    <% end %>
  </div>
</section>

app/views/shared/_search_form.html.erb
<%= form_for :search, url: '', id: 'sitewide_search' do |f| %>
  <%= f.label :search_text, 'Search Text' %>
  <%= f.text_field :search_text, autocomplete: 'off', accesskey: 's' %>
<% end %>

app/views/shared/_settings_navigation.html.erb
<div class="main-sidebar settings-sidebar">
  <section class="subscriptions-nav first">
    <h1>My Account</h1>
    <ul>
      <li class="subscriptions"><%= link_to 'My Subscriptions', ms_path(subscriptions_path) %></li>
      <li class="coupons"><%= link_to 'My Coupons', ms_path(coupons_path) %></li>
      <li class="settings parent">
        <%= link_to 'My Settings', ms_path(edit_settings_path) %>
        <ul>
          <li class="personal"><%= link_to 'Personal Info', ms_path(edit_settings_path) %></li>
          <li class="billing"><%= link_to 'Billing Info', ms_path(billing_info_path) %></li>
          <li class="shipping"><%= link_to 'Shipping Info', ms_path(shipping_infos_path) %></li>
          <li class="password"><%= link_to 'Password', ms_path(edit_password_settings_path) %></li>
        </ul>
      </li>
    </ul>
  </section>
</div>

app/views/shared/_sidebar.html.erb
<div class="main-sidebar">
  <section class="discover first">
    <h1>Discover</h1>
    <ul>
      <li class="handpicked">
        <%= link_to_unless filter_params[:discover] == 'handpicked', 'Handpicked', filtered_plans_path(filter: { discover: 'handpicked' }) %>
      </li>
      <li class="popular">
        <%= link_to_unless filter_params[:discover] == 'popular', 'Most Popular', filtered_plans_path(filter: { discover: 'popular' }) %></li>
      <li class="latest">
        <%= link_to_unless filter_params[:discover] == 'latest', 'Latest Additions', filtered_plans_path(filter: { discover: 'latest' }) %>
      </li>
    </ul>
  </section>

  <section class="categories">
    <h1>Categories</h1>
    <ul class="category-group-list">
      <li><%= link_to_unless_current 'Everything', filtered_plans_path(filter: { discover: 'everything' }) %></li>
      <% @grouped_categories.each do |category_group, categories| %>
        <% is_current = [@category_group, @category.try(:category_group), (@plan && @plan.categories.first.try(:category_group))].include?(category_group) %>
        <li class="parent">
          <%= link_to(category_group.name, category_group, class: "#{is_current ? 'current' : ''}") %>
          <ul class="<%= is_current ? '' : 'hidden' %>">
            <% categories.each do |category| %>
              <% if @plan && @plan.categories.first == category %>
                <li class="current"><%= link_to(category.name, category) %></li>
              <% else %>
                <li><%= link_to_unless_current(category.name, category) %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
      <% end %>
      <li><%= link_to_unless_current 'More', filtered_plans_path(filter: { discover: 'more' }) %></li>
    </ul>
  </section>

  <section class="superhubs">
    <h1>Trending</h1>
    <ul>
      <li><%= link_to_unless_current('Beverages', superhub_path('beverages')) %></li>
      <li><%= link_to_unless_current('Farmers Market', superhub_path('farmers_market')) %></li>
       <li><%= link_to_unless_current('Gifts', superhub_path('gifts')) %></li>
      <li><%= link_to_unless_current('Home Accents', superhub_path('home_accents')) %></li>
      <li><%= link_to_unless_current('Local Services', superhub_path('local_services')) %></li>
      <li><%= link_to_unless_current('Pets', superhub_path('pets')) %></li>
      <li><%= link_to_unless_current('Snacks', superhub_path('snacks')) %></li>
    </ul>
  </section>

  <section class="filters">
    <h1>Filters</h1>
    <%= form_for :filter, url: filtered_plans_path, method: :get do |f| %>
      <%= f.hidden_field :discover, value: filter_params[:discover] %>
      <p><%= f.label :plan_type %> <%= f.select :plan_type, grouped_options_for_select(plan_type_filter, filter_params[:plan_type]) %></p>
      <%= f.text_field :min_price, value: filter_params[:min_price] %>
      <%= f.text_field :max_price, value: filter_params[:max_price] %>
      <div id="sidebar_price_slider"></div>
      <p><%= f.submit 'Filter', class: 'btn fifthary' %></p>
    <% end %>
  </section>
  <div id="map-canvas"></div>
</div>

app/views/shared/_tracking_codes.html.erb
<!-- Remarketing List -->
<script type="text/javascript">
  /* <![CDATA[ /
  var google_conversion_id = 942611472;
  var google_conversion_language = "en";
  var google_conversion_format = "3";
  var google_conversion_color = "ffffff";
  var google_conversion_label = "AnjSCPCXlQQQkLi8wQM";
  var google_conversion_value = 0;
  / ]]> */
</script>

<!-- Google Ads Conversion js -->
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js"></script>
<noscript>
  <div style="display:inline;">
  <img height="1" width="1" style="border-style:none;" alt="" src="https://www.googleadservices.com/pagead/conversion/942611472/?value=0&amp;label=AnjSCPCXlQQQkLi8wQM&amp;guid=ON&amp;script=0"/>
  </div>
</noscript>

<!-- SnapABug (Support Chat) -->
<script type="text/javascript">
  document.write(unescape("%3Cscript src='" + ((document.location.protocol=="https:")?"https://snapabug.appspot.com":"http://www.snapengage.com") + "/snapabug.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
  SnapABug.setButton("/assets/help.png");
  SnapABug.addButton("18fd8833-aaea-4d43-81b8-f70ca8e4f695","4","75%");
</script>

<!-- AdRoll Retargeting Campaign -->
<script type="text/javascript">
adroll_adv_id = "2M6XT2PAIRA7BLRM42LWYD";
adroll_pix_id = "UGWESE75H5CQPE5G4T7SLD";
(function () {
var oldonload = window.onload;
window.onload = function(){
   __adroll_loaded=true;
   var scr = document.createElement("script");
   var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
   scr.setAttribute('async', 'true');
   scr.type = "text/javascript";
   scr.src = host + "/j/roundtrip.js";
   ((document.getElementsByTagName('head') || [null])[0] ||
    document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
   if(oldonload){oldonload()}};
}());
</script>