config/routes.rb
require 'merchant_storefront_constraint'

Monthly::Application.routes.draw do

  # Authentication callbacks
  match "auth/:provider/callback" => 'authentications#create'
  match "auth/failure" => 'authentications#failure'

  # Resources
  resources :category_groups, only: [:show]
  resources :categories, only: [:index, :show] do
    collection do
      get :highlights
    end
  end
  resources :tags, only: [:show] do
    member do
      get :highlights
    end
  end
  resources :merchants, only: [:new, :create] do
    member do
      get :thank_you
      get :terms
    end
  end
  resources :subscriptions do
    member do
      get :confirm_destroy
      post :reactivate
      get :confirm_reactivate
      get :thank_you
    end
    collection do
      get :totals
    end
  end
  resources :user_preferences, only: [:index, :create, :destroy] do
    collection do
      get :my_preferences
    end
  end
  resources :authentications, only: [:index, :create, :destroy]
  resources :plans, only: [:index, :show] do
    collection do
      get :filtered
    end
    member do
      get :preview
      get :summary
      get :subscription_archive
    end
    resource :configurator, controller: 'plan_configurators', only: [] do
      get :zipcode_confirmation
      post :zipcode_confirmation, action: :zipcode_confirmation_submit
      # Plans#show js routes
      get :display_totals

      # Configurator only stuff
      get :coupon_valid
      get :checkout
      get :confirmation
      post :submit
      post :submit_shipping_info
    end
  end
  resource :settings, controller: 'settings', only: [:edit, :update] do
    collection do
      get :persistent_dismiss
      get :edit_password
      put :update_password
      get :update_location
      post :enter_zip
    end
  end
  resource :billing_info, only: [:new, :show, :edit, :destroy] do
    post :callback
    get :delete
  end
  resources :shipping_infos, except: [:show] do
    member do
      get :edit_confirmation
      get :delete
    end
  end
  resources :coupons, only: [:index] do
    collection do
      get :search
    end
  end
  resources :newsletter_subscribers, only: [:create]
  resources :superhubs, only: [:show]
  resource :search, only: [ :show ]

  # Redeem is Coupons#index
  get 'redeem', to: 'coupons#index', as: :coupons_index

  resources :friends, only: [:new, :create]

  # Active Admin
  begin
    ActiveAdmin.routes(self)
    get '/admin/tags/:id' => 'admin/keyword_tags#show', as: :admin_tag
    get '/admin/transactions/:id' => 'admin/transactions#show', as: :admin_transaction
  rescue ActiveRecord::StatementInvalid, PG::Error
    # See #504 for the problem that prompts this horrible begin/rescue.
    warn "ActiveAdmin tried to access the database, but it's not ready"
  end

  namespace :admin do
    constraints CanAccessResque do
      mount Resque::Server, at: '/resque'
    end
  end

  # Users
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' } do
    get 'sessions/form' => 'sessions#form'
    get 'registrations/form' => 'registrations#form'
    get 'passwords/confirmation' => 'passwords#confirmation'
  end
  as :user do
    post 'user_location' => 'sessions#user_location'
    put 'inactivate' => 'registrations#inactivate', as: :inactivate_user_registrations
    get '/users/sign_out' => 'sessions#destroy'

    # Coupons registration
    get 'users/:coupon_name' => 'registrations#new_with_coupon', as: :coupon_registration
    post 'users/create_with_coupon' => 'registrations#create_with_coupon', as: :create_with_coupon
    match '/register_and_get_a_coupon' => redirect('/users/register_5_dollar_coupon')
  end

  # Static pages
  static_routes = %w(
    home
    deals
    featured
    coming_soon
    about
    how-it-works
    terms_of_service
    affiliate_program
    privacy_policy
    why-monthlys
    what-is-monthlys
    jobs
    quality
    guarantee
    contact
    affiliate-program
    sitemap
    record
    beer
  )
  static_routes.each do |action_name|
    get action_name, to: "pages##{action_name.underscore}", as: action_name.underscore
  end

  post 'contact', to: 'pages#contact_submit'

  # Business static pages (merchant marketing site)
  get "business", to: 'business#home'
  get "business/merchants"
  get "business/platform"
  get "business/marketplace"
  get "business/features"
  get "business/reviews"
  get "business/why"
  get "business/custom"
  get "business/categories"
  get "business/developers"

  # Facebook static pages
  get 'facebook/handpicked', to: 'facebook#handpicked'
  get 'facebook/get_10_off', to: 'facebook#get_10_off'

  # Mail web routes
  get 'mail/affiliate_program', to: 'mail#affiliate_program'
  get 'mail/daily_3', to: 'mail#daily_3'
  get 'mail/grand_opening/:id', to: 'mail#grand_opening'
  get 'mail/coupon_invite_5_friends/:id', to: 'mail#coupon_invite_5_friends'
  get 'mail/coupon_invited_5_friends/:id', to: 'mail#coupon_invited_5_friends'
  get 'mail/coupon_sign_up/:id', to: 'mail#coupon_sign_up'
  get 'mail/coupon_signed_up/:id', to: 'mail#coupon_signed_up'
  get 'mail/coupon_signed_up_10/:id', to: 'mail#coupon_signed_up_10'
  get 'mail/new_merchant/:id', to: 'mail#new_merchant'
  get 'mail/new_preference/:id', to: 'mail#new_preference'
  get 'mail/new_user/:id', to: 'mail#new_user'
  get 'mail/new_user_set_preferences/:id', to: 'mail#new_user_set_preferences'
  get 'mail/set_preferences_reminder', to: 'mail#set_preferences_reminder'
  get 'mail/welcome_channel_leads', to: 'mail#welcome_channel_leads'
  get 'mail/popular_national_subscriptions', to: 'mail#popular_national_subscriptions'
  get 'mail/fathers_day', to: 'mail#fathers_day'
  get 'mail/reactivate_email/:id', to: 'mail#reactivate_email', as: 'reactivate_email'

  # Notification web routes
  get 'mail/giftee_email/:id', to: 'notification_mailer#send_giftee_subscription_email'
  get 'mail/shipments/:id', to: 'notification_mailer#send_user_tracking_number_email', as: 'shipment_email'

  # Root
  root to: 'pages#featured'
  #root to: 'plans#filtered', defaults: { filter: { discover: 'handpicked' } }

  # Marketing
  namespace :marketing, module: 'marketing' do
    resources :newsletters, only: [:show]
    resources :user_attachments, only: [:new, :create]
    resources :pages do
      collection do
        get :rewards
      end
    end
  end
  get 'rewards', to: 'marketing/pages#rewards', as: :rewards

  get 'stickit' => 'marketing/user_attachments#new', as: :stickit

  # Merchant storefront
  scope ':custom_site_url', module: 'merchant_storefront', as: 'merchant_storefront', constraints: MerchantStorefrontSiteConstraint.new do
    match '/', to: 'plans#home'

    resources :plans, only: [:index] do
      collection do
        get :home
      end
    end

    get '/how_it_works', to: 'pages#how_it_works'
    get '/contact', to: 'pages#contact'
    get '/about', to: 'pages#about'
    post '/contact', to: 'pages#contact_submit'
  end

  scope ':custom_site_url', constraints: MerchantStorefrontSiteConstraint.new do
    # Resources
    resources :subscriptions, only: [:index, :show, :destroy] do
      member do
        get :confirm_destroy
        post :reactivate
        get :confirm_reactivate
        get :thank_you
      end
      collection do
        get :totals
      end
    end
    resources :coupons, only: [:index] do
      collection do
        get :search
      end
    end
    resources :plans, only: [:index, :show] do
      collection do
        get :filtered
      end
      member do
        get :preview
      end
      resource :configurator, controller: 'plan_configurators', only: [] do
        # Plans#show js routes
        get :display_totals

        # Configurator only stuff
        get :checkout
        get :confirmation
        get :coupon_valid
        post :submit
        post :submit_billing_info
        post :submit_shipping_info
      end
    end
    resource :settings, controller: 'settings', only: [:edit, :update] do
      get :edit_password
      put :update_password
    end
    resource :billing_info, only: [:new, :show, :edit, :destroy] do
      post :callback
      get :delete
    end
    resources :shipping_infos, except: [:show] do
      member do
        get :edit_confirmation
        get :delete
      end
    end

    # Sign out path
    as :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
  end
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base

  has_many :plans
  has_many :subscriptions, through: :plans
  has_and_belongs_to_many :cities
  has_and_belongs_to_many :zipcodes
  has_and_belongs_to_many :states
  has_many :shipping_prices, dependent: :destroy
  has_many :tax_rates, dependent: :destroy
  has_many :users
  has_and_belongs_to_many :faqs
  has_and_belongs_to_many :related_merchants, class_name: 'Merchant', foreign_key: 'related_merchant_id'
  has_many :related_plans, through: :related_merchants, source: :plans

  attr_accessor :zipcodes_list
  accepts_nested_attributes_for :shipping_prices, allow_destroy: true
  accepts_nested_attributes_for :tax_rates

  # ET integration
  include Monthly::ExactTarget::Emailable
  acts_as_exact_target_subscriber(attributes: [:business_name, :location])

  mount_uploader :image, ImageUploader do
    process :resize_to_fill => [76, 76]
  end
  mount_uploader :about_image, ImageUploader do
    process :resize_to_fit => [1150, nil]
  end
  mount_uploader :logo, MerchantLogoUploader
  mount_uploader :storefront_logo, ImageUploader

  before_validation :update_location
  geocoded_by :location, :latitude => :lat, :longitude => :lng
  after_validation :geocode, :if => :location_changed? # auto-fetch coordinates

  module DELIVERY_TYPE
    NATIONWIDE = 1
    CITY_LIST = 2
    ZIPCODE_LIST = 4
    STATE_LIST = 5
  end

  # Validations
  # This validations apply both to AA and the merchant form on the business site.
  validates :business_name, :contact_name, :contact_last_name, :presence => true
  validates :business_name, uniqueness: true
  validates :email, length: { maximum: 100 }, format: { with: Monthly::Application.config.app_config.email_validation_regex }, presence: true
  validates :zipcode, format: { with: /(^\d{5}(-\d{4})?$)|(^$)/, message: 'should be in the form 12345 or 12345-1234' }
  validates :terms, acceptance: true
  validates :delivery_type, inclusion: {
    in: [
      DELIVERY_TYPE::NATIONWIDE,
      DELIVERY_TYPE::CITY_LIST,
      DELIVERY_TYPE::ZIPCODE_LIST,
      DELIVERY_TYPE::STATE_LIST
    ]
  }
  validates :custom_message_type, inclusion: { in: [:shipment_message, :monthlys_message, :none] }
  validates :cutoff_day, inclusion: { in: (1..28) }

  # validates :taxation_policy, inclusion: { in: ['no_taxes', 'tax_plans' 'tax_plans_plus_shippings'] }
  validates :cities, length: { minimum: 1, if: :city_list? }
  validates :states, length: { minimum: 1, if: :state_list? }
  # validates :phone, format: { with: /\A(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?\z/ }
  validate :at_least_one_zipcode, if: :zipcode_list?
  validate :is_user_valid
  validate :cutoff_changed_without_subscriptions

  validates :custom_site_url, uniqueness: true, allow_nil: true,
    format: {
      with: /^(\w[\w-]{4,})?$/,
      message: "should only contain numbers, letters and hyphens (-) and at least 5 characters.",
      allow_nil: true
    }

  default_scope order('merchants.business_name ASC')
  scope :is_active, where({ is_active: true })
  scope :is_inactive, where({ is_active: false })
  scope :is_prospect, where({ is_prospect: true })

  # We are not sending activation emails until the MP is ready
  # after_save :send_activation_email, :if => "self.is_active_changed? && self.is_active?"

  def is_active?
    is_active
  end

  # def send_activation_email
  #   Resque.enqueue(ActivateMerchantNotifierJob, id)
  # end

  def nationwide?
    delivery_type == DELIVERY_TYPE::NATIONWIDE
  end

  def state_list?
    delivery_type == DELIVERY_TYPE::STATE_LIST
  end

  def city_list?
    delivery_type == DELIVERY_TYPE::CITY_LIST
  end

  def zipcode_list?
    delivery_type == DELIVERY_TYPE::ZIPCODE_LIST
  end

  def has_one_plan_only?
    self.plans.count == 1
  end

  def self.nationwide
    where(:delivery_type => NATIONWIDE)
  end

  def update_location
    self.location = "#{address1} #{address2}, #{city}, #{state}, #{country}"
  end

  def to_s
    self.business_name.to_s
  end

  def custom_message_type
    self[:custom_message_type].to_sym
  end

  def subscriptions_count
    subscriptions.count # + plans.select('initial_count').map {|p| p.initial_count }.inject(0, :+)
  end

  def cheapest_plan
    self.plans.min {|p| p.cheapest_plan_recurrence.monthly_cost }
  end

  def at_least_one_zipcode
    errors.add(:zipcodes, " number must be at least 1 if you select zipcode list as delivery type.") unless zipcodes.any?
  end

  def zipcodes_list=(value)
    self[:zipcodes_list] = value
    self.zipcodes = []
    if zipcode_list?
      zipcodes_str = value.split(',').uniq.map {|zip| zip.strip }
      zipcodes_db = Zipcode.where("number IN (?)", zipcodes_str).all
      zipcodes_str.each do |zipcode_str|
        zipcode = zipcodes_db.find {|zip| zip.number == zipcode_str } || Zipcode.new(:number => zipcode_str)
        if zipcode.valid?
          self.zipcodes << zipcode
        else
          errors.add(:zipcodes, "Invalid zipcode: #{zipcode_str}")
        end
      end
    end
  end

  def delivery_area_description
    case self.delivery_type
    when DELIVERY_TYPE::NATIONWIDE then 'Nationwide'
    when DELIVERY_TYPE::CITY_LIST then self.cities_list
    when DELIVERY_TYPE::ZIPCODE_LIST then self.zipcodes_list
    when DELIVERY_TYPE::STATE_LIST then self.states_list
    end
  end

  def shipping_cost_description
    case self.shipping_type
    when 'free' then 'Free'
    when 'flat_rate' then "Flat rate of $#{self.shipping_rate}"
    when 'state_dependant' then self.shipping_prices.map {|sp| "#{sp.state}: #{sp.percentage}% " }.to_sentence
    end
  end

  def zipcodes_list
    self[:zipcodes_list] || zipcodes.map(&:number).join(', ')
  end

  def states_list
    states.map {|state| state.code }.join(', ')
  end

  def cities_list
    cities.join(', ')
  end

  def supports_zipcode?(zipcode) # WARNING: this method should always return true/false since it's used directly on plans#show JSON
    return false if zipcode.blank? || zipcode.city.nil?
    # TODO: this isn't the right place to include this code.. Move somewhere else.
    if nationwide?
      true
    elsif zipcode_list?
      self.zipcodes.map(&:id).include?(zipcode.id) # self.zipcodes.include?(zipcode)
    elsif city_list?
      self.cities.map(&:id).include?(zipcode.city_id) # self.cities.include?(zipcode.city)
    elsif state_list?
      self.states.map(&:id).include?(zipcode.state.id) # self.states.include?(zipcode.state)
    end
  end

  def supports_city?(city)
    return false if city.blank? || city.state.nil?
    # TODO: this isn't the right place to include this code.. Move somewhere else.
    if nationwide?
      true
    elsif city_list?
      self.cities.map(&:id).include?(city.id) # self.cities.include?(zipcode.city)
    elsif state_list?
      self.states.map(&:id).include?(city.state_id) # self.states.include?(zipcode.state)
    else
      false
    end
  end

  def users_attributes=(user_attributes_list)
    user_attributes_list.each do |user_attributes|
      # user_attributes.first is the index of the element in the array.
      new_user = self.users.new(user_attributes.second)
      new_user.is_active = true
    end
  end

  def is_user_valid
    if self.users.any? && !self.users.first.valid?
      self.users.first.errors.full_messages.each {|user_error| self.errors.add(:users, user_error) }
    end
  end

  def shipping_prices_attributes=(shipping_prices_list)
    self.shipping_prices = []
    shipping_prices_list.each do |shipping_price_attributes|
      self.shipping_prices.new(shipping_price_attributes.second) # TODO: figure out why second
    end
  end

  def tax_rates_attributes=(tax_rates_list)
    self.tax_rates = []
    tax_rates_list.each do |tax_rate_attributes|
      self.tax_rates.new(tax_rate_attributes.second)
    end
  end

  # this will be used by the exact target email recipient table
  # or, within exact target, the subscriber list, to be able to filter
  # what type of user is represented by a given email address.  you will
  # want to end up customizing this to fit your needs better
  def exact_target_subscriber_type
    "merchant"
  end

  def cutoff_changed_without_subscriptions
    !(subscriptions.any? && cutoff_day_changed?)
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/admin/merchants/_form.html.erb
<%= semantic_form_for [:admin, @merchant] do |f| %>
  <%= f.inputs do %>
    <%= f.input :business_name %>
    <%= f.input :marketing_phrase %>
    <%= f.input :commission_rate, hint: 'In percentage' %>
    <%= f.input :first_installment, hint: 'In percentage' %>
    <%= f.input :cutoff_day, input_html: { disabled: @merchant.subscriptions.any? }, hint: 'This field will only be enabled for merchants without subscriptions.' %>
    <%= f.input :email %>
    <%= f.input :contact_name %>
    <%= f.input :contact_last_name %>
    <%= f.input :phone %>
    <%= f.input :website %>
    <%= f.input :is_active, :label => "Is active?" %>
    <%= f.input :terms_of_service, :hint => "Markdown is available for this field." %>
    <%= f.input :custom_message_type, as: :select, include_blank: false, collection: [
      ['Don\'t allow gift messages.', 'none'],
      ['Allow message on shipment and gift emails.', 'shipment_message'],
      ['Do not allow message on shipment, but allow gift emails.', 'monthlys_message']
    ] %>
  <% end %>

  <%= f.inputs do %>
    <%= f.input :address1 %>
    <%= f.input :address2 %>
    <%= f.input :zipcode %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :country, :as => :string %>
    <%= f.input :show_location, :default => true %>
  <% end %>

  <%= f.inputs do %>
    <%= f.input :video_url, :hint => "Input the youtube URL as it is, like: 'http://www.youtube.com/watch?v=XXXXXX', where XXXXXX is the video ID on youtube." %>
    <%= f.input :image, :as => :file, :hint => "Image ideal size: 76x76px"%>
    <%= f.input :logo, :as => :file, :hint => "Image ideal proportion: Square. The system will generate 2 versions of this image automatically (55x55 and 115x115px)."%>
  <% end %>

  <h2>Area of service Availability</h2>
  <fieldset class="inputs custom-fieldset">
    <p>
      <%= f.radio_button :delivery_type, Merchant::DELIVERY_TYPE::NATIONWIDE %>
      <%= f.label :"delivery_type_#{Merchant::DELIVERY_TYPE::NATIONWIDE}", 'Nationwide' %>
    </p>
    <p>
      <%= f.radio_button :delivery_type, Merchant::DELIVERY_TYPE::CITY_LIST %>
      <%= f.label :"delivery_type_#{Merchant::DELIVERY_TYPE::CITY_LIST}", 'In the following cities:' %>
      <%= f.select :city_ids, City.all.map{|city| [city.to_s, city.id] }, {}, {:multiple => "multiple"} %>
      <% if @merchant.errors.size > 0 && @merchant.city_list? && @merchant.cities.empty? %>
        <p class="field-error-message">Please select at least one city.</p>
      <% end %>
    </p>
    <p>
      <%= f.radio_button :delivery_type, Merchant::DELIVERY_TYPE::STATE_LIST %>
      <%= f.label :"delivery_type_#{Merchant::DELIVERY_TYPE::STATE_LIST}", 'In the following states:' %>
      <%= f.select :state_ids, State.all.map {|state| [state.code, state.id] }, {}, { multiple: "multiple" } %>
      <% if @merchant.errors.size > 0 && @merchant.state_list? && @merchant.states.empty? %>
        <p class="field-error-message">Please select at least one state.</p>
      <% end %>
    </p>
    <p>
      <%= f.radio_button :delivery_type, Merchant::DELIVERY_TYPE::ZIPCODE_LIST %>
      <%= f.label :"delivery_type_#{Merchant::DELIVERY_TYPE::ZIPCODE_LIST}", 'In the following zipcodes' %>
      <%= f.text_field :zipcodes_list %>
      <% if @merchant.errors.size > 0 && @merchant.zipcode_list? && @merchant.zipcodes.empty? %>
        <p class="field-error-message">Invalid zipcodes provided.</p>
      <% end %>
    </p>
  </fieldset>

  <h2>Shipping Rates <span>per service</span></h2>
  <fieldset id="shipping-types" class="inputs custom-fieldset">
    <p>
      <%= f.radio_button :shipping_type, 'free' %>
      <%= f.label :shipping_type_free, 'Free' %>
    </p>
    <p class="hint">Shipping has no cost or it's included on the plan's price.</p>

    <p>
      <%= f.radio_button :shipping_type, 'flat_rate' %>
      <%= f.label :shipping_type_flat_rate, 'Flat Rate' %>
    </p>
    <p class="hint">Shipping to every possible delivery address costs the same.</p>

    <div id="flat_rate" class="hidden">
      <%= f.label :shipping_rate, 'Enter a shipping rate' %> (in USD)
      <%= f.text_field :shipping_rate %>
    </div>

    <p>
      <%= f.radio_button :shipping_type, 'state_dependant' %>
      <%= f.label :shipping_type_state_dependant, 'State Dependant' %>
    </p>
    <p class="hint">Shipping to each different state has a different shipping percentage associated to it. <br/>
      This percentage is calculated over the total recurring amount of the subscription (plan price + selected option prices).</p>

    <ul id="state_dependant" class="hidden">
      <%= f.fields_for :shipping_prices do |shipping_price| %>
        <li>
          <%= shipping_price.label :percentage, shipping_price.object.state.code %>
          <%= shipping_price.text_field :percentage %>% /service
          <%= shipping_price.text_field :state_id, class: 'hidden' %>
        </li>
      <% end %>
    </ul>
  </fieldset>

  <h2>Taxation Policy</h2>
  <fieldset id="tax-policy" class="inputs custom-fieldset">
    <p>
      <%= f.radio_button :taxation_policy, 'no_taxes' %>
      <%= f.label :taxation_policy_no_taxes, 'I\'m not required to add taxes' %>
    </p>
    <p>
      <%= f.radio_button :taxation_policy, 'tax_plans' %>
      <%= f.label :taxation_policy_tax_plans, 'I\'m required to add taxes over my products/services' %>
    </p>
    <p>
      <%= f.radio_button :taxation_policy, 'tax_plans_plus_shippings' %>
      <%= f.label :taxation_policy_tax_plans_plus_shippings, 'I\'m required to add taxes over my products/services plus their shipping expenses' %>
    </p>
  </fieldset>

  <div id="tax-rates" class="hidden">
    <h2>Taxation Rates</h2>
    <fieldset class="inputs custom-fieldset">
      <ul>
        <%= f.fields_for :tax_rates do |tax_rate| %>
          <li>
            <%= tax_rate.label :percentage, tax_rate.object.state.code %>
            <%= tax_rate.text_field :percentage %>%
            <%= tax_rate.text_field :state_id, class: 'hidden' %>
          </li>
        <% end %>
      </ul>
    </fieldset>
  </div>

  <h2>Custom Storefront</h2>
  <%= f.inputs :id => 'storefront' do %>
    <%= f.input :custom_site, :label => "Has a custom storefront?" %>
    <%= f.input :custom_site_url, :hint => "The name of the merchant with hyphens(-) instead of spaces, example 'wonder-bakery'." %>
    <%= f.input :custom_site_base_color, :hint => "A color in hex, example: '5b396b'." %>
    <%= f.input :storefront_heading, :label => "Heading" %>
    <%= f.input :tagline %>
    <%= f.input :about, :hint => "A brief story about the merchant. You may use markdown in this field." %>
    <%= f.input :faqs %>
    <%= f.input :facebook_url %>
    <%= f.input :twitter_url %>
    <%= f.input :storefront_logo, :as => :file, :hint => "No size contraints for this one."%>
    <%= f.input :about_image, :as => :file, :hint => "Image ideal size: 1150x430px"%>
    <%= f.input :related_merchants %>
  <% end %>

  <%= f.buttons :commit %>
<% end %>
<script type="text/javascript" src="/assets/admin/merchants/edit.js"></script>

app/views/admin/merchants/_sidebar_index.html.erb
<%= link_to 'General Reports', global_reports_admin_merchants_path %>

app/views/admin/merchants/global_reports.html.erb
<script type="text/javascript" src="/assets/admin/highcharts.js"></script>

<%= high_chart("users_subscribers", @users_subscribers) %>
<div id="users_subscribers" style="min-width: 400px; height: 400px; margin: 0 auto"></div>


<%#= high_chart("subscribers_merchants", @subscribers_merchants) %>
<%# <div id="subscribers_merchants" style="min-width: 400px; height: 400px; margin: 0 auto"></div>%>

app/views/admin/merchants/reports.html.erb
<script type="text/javascript" src="/assets/admin/highcharts.js"></script>

<%= high_chart("subscribers", @subscribers) %>
<div id="subscribers" style="max-width: 100%; width: 500px; height: 300px;"></div>

<%= high_chart("plans_chart", @plans_chart) %>
<div id="plans_chart" style="width: 500px; height: 300px;"></div>