config/routes.rb
require 'merchant_storefront_constraint'

Monthly::Application.routes.draw do

  # Authentication callbacks
  match "auth/:provider/callback" => 'authentications#create'
  match "auth/failure" => 'authentications#failure'

  # Resources
  resources :category_groups, only: [:show]
  resources :categories, only: [:index, :show] do
    collection do
      get :highlights
    end
  end
  resources :tags, only: [:show] do
    member do
      get :highlights
    end
  end
  resources :merchants, only: [:new, :create] do
    member do
      get :thank_you
      get :terms
    end
  end
  resources :subscriptions do
    member do
      get :confirm_destroy
      post :reactivate
      get :confirm_reactivate
      get :thank_you
    end
    collection do
      get :totals
    end
  end
  resources :user_preferences, only: [:index, :create, :destroy] do
    collection do
      get :my_preferences
    end
  end
  resources :authentications, only: [:index, :create, :destroy]
  resources :plans, only: [:index, :show] do
    collection do
      get :filtered
    end
    member do
      get :preview
      get :summary
      get :subscription_archive
    end
    resource :configurator, controller: 'plan_configurators', only: [] do
      get :zipcode_confirmation
      post :zipcode_confirmation, action: :zipcode_confirmation_submit
      # Plans#show js routes
      get :display_totals

      # Configurator only stuff
      get :coupon_valid
      get :checkout
      get :confirmation
      post :submit
      post :submit_shipping_info
    end
  end
  resource :settings, controller: 'settings', only: [:edit, :update] do
    collection do
      get :persistent_dismiss
      get :edit_password
      put :update_password
      get :update_location
      post :enter_zip
    end
  end
  resource :billing_info, only: [:new, :show, :edit, :destroy] do
    post :callback
    get :delete
  end
  resources :shipping_infos, except: [:show] do
    member do
      get :edit_confirmation
      get :delete
    end
  end
  resources :coupons, only: [:index] do
    collection do
      get :search
    end
  end
  resources :newsletter_subscribers, only: [:create]
  resources :superhubs, only: [:show]
  resource :search, only: [ :show ]

  # Redeem is Coupons#index
  get 'redeem', to: 'coupons#index', as: :coupons_index

  resources :friends, only: [:new, :create]

  # Active Admin
  begin
    ActiveAdmin.routes(self)
    get '/admin/tags/:id' => 'admin/keyword_tags#show', as: :admin_tag
    get '/admin/transactions/:id' => 'admin/transactions#show', as: :admin_transaction
  rescue ActiveRecord::StatementInvalid, PG::Error
    # See #504 for the problem that prompts this horrible begin/rescue.
    warn "ActiveAdmin tried to access the database, but it's not ready"
  end

  namespace :admin do
    constraints CanAccessResque do
      mount Resque::Server, at: '/resque'
    end
  end

  # Users
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' } do
    get 'sessions/form' => 'sessions#form'
    get 'registrations/form' => 'registrations#form'
    get 'passwords/confirmation' => 'passwords#confirmation'
  end
  as :user do
    post 'user_location' => 'sessions#user_location'
    put 'inactivate' => 'registrations#inactivate', as: :inactivate_user_registrations
    get '/users/sign_out' => 'sessions#destroy'

    # Coupons registration
    get 'users/:coupon_name' => 'registrations#new_with_coupon', as: :coupon_registration
    post 'users/create_with_coupon' => 'registrations#create_with_coupon', as: :create_with_coupon
    match '/register_and_get_a_coupon' => redirect('/users/register_5_dollar_coupon')
  end

  # Static pages
  static_routes = %w(
    home
    deals
    featured
    coming_soon
    about
    how-it-works
    terms_of_service
    affiliate_program
    privacy_policy
    why-monthlys
    what-is-monthlys
    jobs
    quality
    guarantee
    contact
    affiliate-program
    sitemap
    record
    beer
  )
  static_routes.each do |action_name|
    get action_name, to: "pages##{action_name.underscore}", as: action_name.underscore
  end

  post 'contact', to: 'pages#contact_submit'

  # Business static pages (merchant marketing site)
  get "business", to: 'business#home'
  get "business/merchants"
  get "business/platform"
  get "business/marketplace"
  get "business/features"
  get "business/reviews"
  get "business/why"
  get "business/custom"
  get "business/categories"
  get "business/developers"

  # Facebook static pages
  get 'facebook/handpicked', to: 'facebook#handpicked'
  get 'facebook/get_10_off', to: 'facebook#get_10_off'

  # Mail web routes
  get 'mail/affiliate_program', to: 'mail#affiliate_program'
  get 'mail/daily_3', to: 'mail#daily_3'
  get 'mail/grand_opening/:id', to: 'mail#grand_opening'
  get 'mail/coupon_invite_5_friends/:id', to: 'mail#coupon_invite_5_friends'
  get 'mail/coupon_invited_5_friends/:id', to: 'mail#coupon_invited_5_friends'
  get 'mail/coupon_sign_up/:id', to: 'mail#coupon_sign_up'
  get 'mail/coupon_signed_up/:id', to: 'mail#coupon_signed_up'
  get 'mail/coupon_signed_up_10/:id', to: 'mail#coupon_signed_up_10'
  get 'mail/new_merchant/:id', to: 'mail#new_merchant'
  get 'mail/new_preference/:id', to: 'mail#new_preference'
  get 'mail/new_user/:id', to: 'mail#new_user'
  get 'mail/new_user_set_preferences/:id', to: 'mail#new_user_set_preferences'
  get 'mail/set_preferences_reminder', to: 'mail#set_preferences_reminder'
  get 'mail/welcome_channel_leads', to: 'mail#welcome_channel_leads'
  get 'mail/popular_national_subscriptions', to: 'mail#popular_national_subscriptions'
  get 'mail/fathers_day', to: 'mail#fathers_day'
  get 'mail/reactivate_email/:id', to: 'mail#reactivate_email', as: 'reactivate_email'

  # Notification web routes
  get 'mail/giftee_email/:id', to: 'notification_mailer#send_giftee_subscription_email'
  get 'mail/shipments/:id', to: 'notification_mailer#send_user_tracking_number_email', as: 'shipment_email'

  # Root
  root to: 'pages#featured'
  #root to: 'plans#filtered', defaults: { filter: { discover: 'handpicked' } }

  # Marketing
  namespace :marketing, module: 'marketing' do
    resources :newsletters, only: [:show]
    resources :user_attachments, only: [:new, :create]
    resources :pages do
      collection do
        get :rewards
      end
    end
  end
  get 'rewards', to: 'marketing/pages#rewards', as: :rewards

  get 'stickit' => 'marketing/user_attachments#new', as: :stickit

  # Merchant storefront
  scope ':custom_site_url', module: 'merchant_storefront', as: 'merchant_storefront', constraints: MerchantStorefrontSiteConstraint.new do
    match '/', to: 'plans#home'

    resources :plans, only: [:index] do
      collection do
        get :home
      end
    end

    get '/how_it_works', to: 'pages#how_it_works'
    get '/contact', to: 'pages#contact'
    get '/about', to: 'pages#about'
    post '/contact', to: 'pages#contact_submit'
  end

  scope ':custom_site_url', constraints: MerchantStorefrontSiteConstraint.new do
    # Resources
    resources :subscriptions, only: [:index, :show, :destroy] do
      member do
        get :confirm_destroy
        post :reactivate
        get :confirm_reactivate
        get :thank_you
      end
      collection do
        get :totals
      end
    end
    resources :coupons, only: [:index] do
      collection do
        get :search
      end
    end
    resources :plans, only: [:index, :show] do
      collection do
        get :filtered
      end
      member do
        get :preview
      end
      resource :configurator, controller: 'plan_configurators', only: [] do
        # Plans#show js routes
        get :display_totals

        # Configurator only stuff
        get :checkout
        get :confirmation
        get :coupon_valid
        post :submit
        post :submit_billing_info
        post :submit_shipping_info
      end
    end
    resource :settings, controller: 'settings', only: [:edit, :update] do
      get :edit_password
      put :update_password
    end
    resource :billing_info, only: [:new, :show, :edit, :destroy] do
      post :callback
      get :delete
    end
    resources :shipping_infos, except: [:show] do
      member do
        get :edit_confirmation
        get :delete
      end
    end

    # Sign out path
    as :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  include PricesHelper

  load_and_authorize_resource
  skip_load_resource only: %w(index canceled expired new create)

  before_filter :ensure_subscription_is_active, only: %w(confirm_destroy destroy)
  before_filter :ensure_subscription_is_not_expired, only: %w(edit update)
  before_filter :ensure_subscription_is_canceled, only: %w(confirm_reactivate reactivate)

  def index
    @active_subscriptions = current_user.subscriptions.has_state(:active)
    @canceled_subscriptions = current_user.subscriptions.has_state(:canceled)
    @expired_subscriptions = current_user.subscriptions.has_state(:expired)
  end

  def show
  end

  def new
    @previous_subscription = current_user.subscriptions.find(params[:previous_subscription_id])
    @subscription = current_user.subscriptions.new

    @plan = @previous_subscription.plan

    return redirect_to subscriptions_path, flash: { error: 'You\'re already subscribed to this plan.' } if current_user.is_subscribed?(@plan)

    @plan_recurrences = @plan.active_plan_recurrences
    @option_groups = @plan.active_option_groups
    @shipping_infos = current_user.shipping_infos.active.all
    @plan_recurrence = @plan_recurrences.find {|pr| pr.id == @subscription.plan_recurrence_id } || @plan_recurrences.first
  end

  def create
    respond_to do |format|
      format.json do
        previous_subscription = current_user.subscriptions.find(params[:previous_subscription_id])
        plan = previous_subscription.plan

        subscription_relations = {
          user: current_user,
          plan: plan,
          plan_recurrence: plan.plan_recurrences.find(subscription_params[:plan_recurrence_id]),
          shipping_info: current_user.shipping_infos.active.find_by_id(subscription_params[:shipping_info_id]),
          options: plan.options.active.where(id: subscription_params[:options_id]).includes(:option_group).all,
          coupon: nil
        }

        validator = SubscriptionsValidator.new(subscription_relations)

        if validator.valid?
          subscription = Monthly::Rapi::Subscriptions.create(subscription_relations.merge({
            is_gift: subscription_params[:is_gift] == '1',
            notify_giftee_on_email: subscription_params[:notify_giftee_on_email] == '1',
            notify_giftee_on_shipment: subscription_params[:notify_giftee_on_shipment] == '1',
            giftee_name: subscription_params[:giftee_name],
            giftee_email: subscription_params[:giftee_email],
            gift_description: subscription_params[:gift_description]
          }))
          if subscription.is_gift? && subscription.notify_giftee_on_email? &&
            Monthly::Application.config.app_config.email_validation_regex =~ subscription.giftee_email
            Resque.enqueue(GifteeSubscriptionJob, subscription.id)
          end
          # Notify the admins about the new subscription
          Resque.enqueue(MerchantSubscriptionJob, subscription.id, :new)
          # Send to the subscription detail with the 'Thank you' message (subscribed_to parameter)
          render json: { status: :success, redirect_to: ms_path(thank_you_subscription_path(subscription)) }
        else
          notify_airbrake("Logged action: #{validator.errors.join(', ')}")
          render json: { status: :error, errors: validator.errors }
        end
      end
    end
  rescue Recurly::Transaction::DeclinedError, Recurly::Transaction::RetryableError => e
    redirect_to subscriptions_path, flash: { error: e.message }
  end

  def edit
    @plan = @subscription.plan
    @plan_recurrences = @plan.active_plan_recurrences
    @option_groups = @plan.active_option_groups.reject(&:onetime?)
    @shipping_infos = current_user.shipping_infos.active.all
    @plan_recurrence = @subscription.plan_recurrence.is_active? ? @subscription.plan_recurrence : @plan_recurrences.first
  end

  def update
    respond_to do |format|
      format.json do
        plan_recurrence = PlanRecurrence.find(subscription_params[:plan_recurrence_id])
        plan = plan_recurrence.plan

        subscription_relations = {
          user: current_user,
          plan: plan,
          plan_recurrence: plan_recurrence,
          shipping_info: current_user.shipping_infos.active.find_by_id(subscription_params[:shipping_info_id]),
          options: plan.options.active.where(id: subscription_params[:options_id]).includes(:option_group).all,
          coupon: nil
        }

        validator = SubscriptionsValidator.new(subscription_relations, @subscription)
        if validator.valid?
          Monthly::Rapi::Subscriptions.reactivate(@subscription) if @subscription.canceled?
          Monthly::Rapi::Subscriptions.update(@subscription, subscription_relations)
          Resque.enqueue(MerchantSubscriptionJob, @subscription.id, :change)
          flash[:success] = 'Subscription updated successfully!'
          render json: { status: :success, redirect_to: subscription_path(@subscription) }
        else
          render json: { status: :error, errors: validator.errors }
        end
      end
    end
  end

  def totals
    respond_to do |format|
      format.json do
        plan_recurrence = PlanRecurrence.find(subscription_params[:plan_recurrence_id])
        plan = plan_recurrence.plan
        shipping_info = (plan.shippable? && current_user.shipping_infos.active.find_by_id(subscription_params[:shipping_info_id])) || nil
        options = plan.options.where(id: subscription_params[:options_id]).includes(:option_group).all

        totals_pricing = SubscriptionManager::TotalsPricing.totals({
          user: current_user,
          plan_recurrence: plan_recurrence,
          options: options,
          shipping_info: shipping_info
        })

        refresh_options = plan.options.active.map do |option|
          { id: option.id, billing_desc: (option.amount.zero?)? 'No additional charge' : "Add $ #{pretty_price(option.amount_per_billing(plan_recurrence))} #{plan_recurrence.billing_desc}" }
        end

        render json: {
          totals: {
            recurrent_without_extras: pretty_price(totals_pricing[:recurrent_without_extras]),
            recurrent_shipping: totals_pricing[:recurrent_shipping] ? pretty_price(totals_pricing[:recurrent_shipping]) : nil,
            recurrent_tax: totals_pricing[:recurrent_tax] ? pretty_price(totals_pricing[:recurrent_tax]) : nil,
            recurrent_total: pretty_price(totals_pricing[:recurrent_total])
          },
          billing_desc: plan_recurrence.billing_recurrence_in_words.capitalize,
          refresh_options: refresh_options
        }
      end
    end
  end

  def thank_you
    load_sidebar_categories
    @invoice = @subscription.invoices.last
  end

  def confirm_destroy
  end

  def destroy
    Monthly::Rapi::Subscriptions.cancel(@subscription)
    # Notify the admins about the subscription cancellation
    Resque.enqueue(MerchantSubscriptionJob, @subscription.id, :cancel)
    redirect_to ms_path(subscriptions_path), flash: { success: 'Subscription canceled successfully' }
  end

  def confirm_reactivate
    @billing_info = Monthly::Rapi::Accounts.billing_info(current_user)
    @plan_recurrence = @subscription.plan_recurrence
    @plan = @plan_recurrence.plan
  end

  def reactivate
    Monthly::Rapi::Subscriptions.reactivate(@subscription)
    # Notify the admins about the subscription reactivation
    Resque.enqueue(MerchantSubscriptionJob, @subscription.id, :reactivate)
    redirect_to ms_path(subscriptions_path), flash: { success: 'Subscription reactivated successfully.' }
  end

private
  def subscription_params
    (params[:subscription] || {}).slice(:plan_recurrence_id, :options_id, :shipping_info_id)
  end

  def ensure_subscription_is_active
    redirect_to(ms_path(subscription_path(@subscription)), flash: { error: 'This subscription is not active' }) unless @subscription.active?
  end

  def ensure_subscription_is_not_expired
    redirect_to(ms_path(subscription_path(@subscription)), flash: { error: 'This subscription is expired' }) if @subscription.expired?
  end

  def ensure_subscription_is_canceled
    redirect_to(ms_path(subscription_path(@subscription)), flash: { error: 'This subscription is not canceled' }) unless @subscription.canceled?
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper

  def subscription_explanation(plan_recurrence, billing_info)
    content_tag(:p) do
      "
        <strong>#{plan_recurrence.pretty_explanation}</strong> 
        will be debited from the card ending in #{billing_info.last_four} 
      ".html_safe
    end
  end
end

app/views/subscriptions/_checkout_totals.html.erb
<script id="checkoutTotals" type="text/x-jquery-tmpl">
  <!--
    Locals:
      - totals
      - billing_desc
      - coupon_desc (optional)
  -->

  <dl>
    <dt>Subtotal</dt>
    <dd>$ ${totals.recurrent_without_extras}</dd>

    {{if totals.recurrent_shipping}}
      <dt>Shipping cost</dt>
      <dd>$ ${totals.recurrent_shipping}</dd>
    {{/if}}

    {{if totals.recurrent_tax}}
      <dt>Taxes</dt>
      <dd>$ ${totals.recurrent_tax}</dd>
    {{/if}}

    {{if totals.recurrent_discount}}
      <dt class="discount">Discount</dt>
      <dd class="discount">$ ${totals.recurrent_discount}</dd>
    {{/if}}

    <dt class="important">${billing_desc} fee</dt>
    <dd class="important">$ ${totals.recurrent_total}</dd>

    {{if totals.first_time_discount}}
      <dt class="discount">
        Today's discount "${coupon_desc}"
      </dt>
      <dd class="discount">$ ${totals.first_time_discount}</dd>
    {{/if}}

    {{if (totals.onetime_total && totals.onetime_total > 0)}}
      <dt>One-time fee(s)</dt>
      <dd>$ ${totals.onetime_total}</dd>
    {{/if}}

    {{if (totals.recurrent_total != totals.first_time_total && totals.first_time_total)}}
      <dt>Today's fee</dt>
      <dd>$ ${totals.first_time_total}</dd>
    {{/if}}
  </dl>
</script>

app/views/subscriptions/_detail.html.erb
<%#
  Locals:
    - subscription
    - view
%>

<article class="subscription<%= ' expired' if subscription.expired? %><%= ' canceled' if subscription.canceled? %><%= ' active' if subscription.active? %>">
  <div class="subscription-actions">
    <% if %w(index show).include?(view) %>
      <% if subscription.canceled? %>
        <%= link_to 'Reactivate', ms_path(confirm_reactivate_subscription_path(subscription)), class: 'btn secondary reactivate' %>
      <% elsif subscription.expired? && subscription.plan.active? %>
        <%= link_to 'Resubscribe', ms_path(new_subscription_path(previous_subscription_id: subscription.id)), class: 'btn secondary resubscribe' %>
      <% end %>

      <% if subscription.expired? %>
        <%= link_to 'Configure', '#', class: 'configure disabled', title: 'Configure' %>
      <% else %>
        <%= link_to 'Configure', ms_path(edit_subscription_path(subscription)), class: 'configure', title: 'Configure this subscription' %>
      <% end %>
    <% end %>
    <% if view == 'index' %>
      <%= link_to 'View', ms_path(subscription_path(subscription)), class: 'view', title: 'View Details' %>
    <% end %>
  </div>

  <%= link_to ms_path(subscription_path(subscription)) do %>
    <%= image_tag subscription.plan.thumbnail.url, class: 'subscription-thumbnail', alt: subscription.plan.name %>
  <% end %>

  <div class="subscription-info">
    <hgroup>
      <% if view == 'index' %>
        <h1 class="plan"><%= link_to subscription.plan.name, ms_path(subscription_path(subscription)) %></h1>
      <% end %>
      <h2 class="merchant">From: <strong><%= subscription.plan.merchant.business_name %></strong></h2>
    </hgroup>

    <dl>
      <dt>Next renewal date:</dt>
      <dd><%= subscription.renewal_date ? subscription.renewal_date.to_s(:short) : 'Will not renew' %></dd>
    </dl>

    <p class="price">
      <strong>Total $ <%= pretty_price(subscription.recurrent_total) %></strong>
      <%= subscription.plan_recurrence.billing_desc %>
    </p>

    <% if subscription.is_past_due? %>
      <% if subscription.expired? %>
        <p class="message flash-error">
          <strong>Payment failure.</strong>
          This subscription expired due to payment errors.
        </p>
      <% else %>
        <p class="message flash-error">
          <strong>This subscription is past due.</strong>
          We will try to collect the payment again in a few days.
          Please <%= link_to 'edit your billing', ms_path(edit_billing_info_path) %> info if necessary.
        </p>
      <% end %>
    <% end %>
  </div>
  <div class="clearfix"></div>
</article>

app/views/subscriptions/_list.html.erb
<ul class="subscriptions-list">
  <% subscriptions.each do |subscription| %>
    <li class="subscriptions-list-item">
      <%= render partial: 'subscriptions/detail', locals: { subscription: subscription, view: 'index' } %>
    </li>
  <% end %>
</ul>

app/views/subscriptions/_list_empty.html.erb
<div class='subscriptions-list-empty'>
  <p class="empty-notice">You do not have any subscriptions at this time. <%= link_to "View subscriptions in your area", root_path, :class => "btn secondary" %>
  </p>
</div>

app/views/subscriptions/_nav.html.erb
<ul class="subscriptions-nav">
  <li class="active"><%= link_to 'Active Subscriptions', subscriptions_path %></li>
  <li class="canceled"><%= link_to 'Canceled Subscriptions', canceled_subscriptions_path %></li>
  <li class="expired"><%= link_to 'Expired Subscriptions', expired_subscriptions_path %></li>
</ul>

app/views/subscriptions/confirm_destroy.html.erb
<h1 class="main">Are you sure you want to <br/>cancel this subscription?</h1>
<div class="modal-form cancellation-confirmation">
  <%= form_for @subscription, url: ms_path(subscription_path), method: :delete, class: 'modal-form' do |f| %>
    <p>
      Cancelling this subscription will cause it to expire on the next renewal date:
      <strong><%= @subscription.renewal_date.to_s(:short) %></strong>.
      On that date, the subscription will not be invoiced again.
    </p>

    <p>Also, if you stay active you could be a <%= link_to 'Gold Member', rewards_path %> and gain access to rewards like:</p>

    <ul>
      <li>Cash Credits &amp; Rewards</li>
      <li>Exclusive Subscriptions</li>
      <li>Free Samples</li>
    </ul>

    <%= link_to 'No, don\'t cancel it', '#', class: 'btn secondary close-modal' %>
    <%= f.submit "Yes, cancel it", class: "btn fifthary" %>
  <% end %>
</div>

app/views/subscriptions/confirm_reactivate.html.erb
<h1 class="main">Reactivate</h1>
<div class="modal-form">
  <%= form_for @subscription, url: ms_path(reactivate_subscription_path(@subscription)), method: :post do |f| %>
    <p>Are you sure you want to reactivate this subscription?</p>
    <%= f.submit 'Reactivate', class: 'btn secondary' %>
  <% end %>
</div>

app/views/subscriptions/show.html.erb
<% content_for(:title) { 'Subscription Details' } %>

<%= render partial: 'shared/settings_navigation' %>

<section class="content">
  <hgroup class="main">
    <h1><%= @subscription.plan.name %></h1>
    <h2 class="breadcrumb"><%= breadcrumbs_for(:subscription, @subscription) %></h2>
  </hgroup>

  <section class="subscription-detail">
    <%= render partial: 'subscriptions/detail', locals: { subscription: @subscription, view: 'show' } %>

    <div class="inner-wrapper">
      <section class="billing-info<%= ' large' if @subscription.shipping_info.nil? %>">
        <h1>Billing Info</h1>
        <% unless @subscription.user.billing_info.nil? %>
          <p class="name"><%= @subscription.user.billing_info.first_name %> <%= @subscription.user.billing_info.last_name %></p>
          <p class="creditcard">XXXX-XXXX-XXXX-<%= @subscription.user.billing_info.last_four %></p>
          <%= link_to 'Edit', edit_billing_info_path, class: 'edit' %>
        <% else %>
          <p class="QA-notes">Billing info is not available on staging for already existing subscription. You may create a new subscription to test this functionality</p>
        <% end %>
      </section>

      <% if @subscription.shipping_info %>
        <section class="shipping-info">
          <h1>Shipping Info</h1>
          <p class="name"><%= @subscription.shipping_info.first_name %> <%= @subscription.shipping_info.last_name %></p>
          <p class="address"><%= @subscription.shipping_info.address1 %> <%= @subscription.shipping_info.address2 %></p>
          <p class="location"><%= @subscription.shipping_info.city %>, <%= @subscription.shipping_info.state %> - <%= @subscription.shipping_info.zipcode %> - United States</p>
          <%= link_to 'Edit', edit_shipping_info_path(@subscription.shipping_info), class: 'edit' %>
        </section>
      <% end %>

      <% if @subscription.invoices.any? %>
        <% if @new_subscription && @new_subscription.first_time_discount %>
          <p class="message flash-notice">Your discount was applied to your first invoice below.</p>
        <% end %>

        <section class="invoices">
          <h1>Invoices</h1>
          <ul>
            <% @subscription.invoices.each do |invoice| %>
              <li class="invoice">
                <p class="quicktotal">$<%= pretty_price(invoice.total_in_usd) %></p>
                <a href="#" class="print">Print</a>
                <h2 class="date"><%= invoice.created_at.to_s(:long) %><span class="id"> - ID <%= invoice.id %></span></h2>
                <ul class="lines">
                  <% invoice.invoice_lines.each do |line| %>
                    <li class="line<%= cycle('', ' even') %>">
                      <p class="amount">$<%= pretty_price(line.unit_amount_in_usd * line.quantity) %></p>
                      <p class="detail"><%= line.description %></p>
                    </li>
                  <% end %>
                  <% if invoice.total_in_usd < invoice.subtotal_in_usd %>
                    <li class="line discount">
                      <p class="amount">$<%= pretty_price(invoice.subtotal_in_usd - invoice.total_in_usd) %></p>
                      <p class="detail">Discount</p>
                    </li>
                  <% end %>
                </ul>

                <p class="total">Total $<%= pretty_price(invoice.total_in_usd) %></p>

                <% if invoice.collected? %>
                  <p class="message flash-success">
                    <strong>Payment received successfully.</strong>
                    This invoice was charged successfully.
                  </p>
                <% elsif invoice.past_due? %>
                  <p class="message flash-error">
                    <strong>This invoice is past due.</strong>
                    We will try to collect the payment again in a few days.
                    Please <%= link_to 'edit your billing', ms_path(edit_billing_info_path) %> info if necessary.
                  </p>
                <% elsif invoice.failed? %>
                  <p class="message flash-error">
                    <strong>Payment failure.</strong>
                    This invoice failed, even after trying 2 more times, due to payment errors.
                  </p>
                <% end %>
              </li>
            <% end %>
          </ul>
        </section>
      <% end %>

      <% if @subscription.shipments.any? %>
        <section class="shipments">
          <h1>Shipments</h1>
          <ul>
            <% @subscription.shipments.each do |shipment| %>
              <li class="shipment">
                <h2 class="date"><%= shipment.created_at.to_s(:long) %><span class="id"> - ID <%= shipment.id %></span></h2>
                <ul class="lines">
                  <li><strong>Date shipped:</strong> <%= shipment.created_at %></li>
                  <li class="even"><strong>Tracking Number:</strong> <%= shipment.tracking_number %></li>
                  <li><strong>Carrier:</strong> <%= shipment.carrier %></li>
                </ul>
              </li>
            <% end %>
          </ul>
        </section>
      <% end %>
    </div>
  </section>
</section>

<% content_for(:javascript) do %>
  <%= requirejs('subscriptions/show') %>
<% end %>